### ISSUE TITLE
h2 font size is substantially larger than h1 due to a styling rule in a partial

### ISSUE THREAD

**Issue by sarhan-a** [sarhan-a/redore#61]
in _how_to_cards.html.erb the how to step numbers are classed as h2
`<div class="h2 text-primary my-2">1</div>
          <div class="ms-3 mt-3">
            <h3 class="h5 card-title">Search Listings</h3>
            <p class="card-text fs-sm">Search for businesses that can collect and recycle your domestic or commercial waste.</p>
            </div>`

and the sizing is defined in in _how_to_cards.scss

`h2 {
  font-size: 4rem;
}
`

I believe h1 is set somewhere else as 2.5rem;   

This makes it unusual and hard to reuse the h2 tags.  
@ozdere could you please refactor the code? Thanks.

**Comment by ozdere** [comment]
Thanks for pointing this out. This issue is fixed with PR #63.
